/* Generated By:JavaCC: Do not edit this line. Analizador_LienzoConstants.java */
package AnalizadorCC;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Analizador_LienzoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGIT = 5;
  /** RegularExpression Id. */
  int ENTERO = 6;
  /** RegularExpression Id. */
  int DECIMAL = 7;
  /** RegularExpression Id. */
  int CADENA = 8;
  /** RegularExpression Id. */
  int CARACTER = 9;
  /** RegularExpression Id. */
  int LIENZO = 10;
  /** RegularExpression Id. */
  int CIERRE = 11;
  /** RegularExpression Id. */
  int ABRE = 12;
  /** RegularExpression Id. */
  int PUBLICO = 13;
  /** RegularExpression Id. */
  int PRIVADO = 14;
  /** RegularExpression Id. */
  int PROTEGIDO = 15;
  /** RegularExpression Id. */
  int EXTIENDE = 16;
  /** RegularExpression Id. */
  int VAR = 17;
  /** RegularExpression Id. */
  int TENTERO = 18;
  /** RegularExpression Id. */
  int TCADENA = 19;
  /** RegularExpression Id. */
  int TBOOLEAN = 20;
  /** RegularExpression Id. */
  int TDOBLE = 21;
  /** RegularExpression Id. */
  int TCARACTER = 22;
  /** RegularExpression Id. */
  int CONSERVAR = 23;
  /** RegularExpression Id. */
  int VOID = 24;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "<DIGIT>",
    "<ENTERO>",
    "<DECIMAL>",
    "<CADENA>",
    "<CARACTER>",
    "\"Lienzo\"",
    "\"?\"",
    "\"\\u00bf\"",
    "\"publico\"",
    "\"privado\"",
    "\"protegido\"",
    "\"extiende\"",
    "\"var\"",
    "\"entero\"",
    "\"cadena\"",
    "\"boolean\"",
    "\"doble\"",
    "\"caracter\"",
    "\"conservar\"",
    "\"void\"",
    "<IDENTIFICADOR>",
    "\"$\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"^\"",
    "\"*\"",
    "\"/\"",
    "\"==\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"!=\"",
    "\"!&\\u00a1\"",
    "\"||\"",
    "\"!||\"",
    "\"&|\"",
    "\"&&\"",
    "\"!&&\"",
  };

}
